import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // ── Custom rules ──────────────────────────────────────────────────────
  {
    name: "owlab/custom-rules",
    rules: {
      // Warn on explicit `any` to encourage proper typing
      "@typescript-eslint/no-explicit-any": "warn",

      // Warn on console.log but allow console.warn and console.error
      "no-console": ["warn", { allow: ["warn", "error"] }],
    },
  },

  // ── Build & maintenance scripts ───────────────────────────────────────
  // CommonJS scripts (.js without ESM "type": "module") legitimately use
  // require(); they are run by Node directly, not bundled.
  {
    name: "owlab/scripts-cjs",
    files: ["scripts/**/*.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },

  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Build artifacts (gitignored, regenerated by pnpm build / fumadocs):
    ".source/**",
    "public/_pagefind/**",
  ]),
]);

export default eslintConfig;
